version: '3'

tasks:
  build: go build --tags "json1 fts5" ./...
  format:
    cmds:
    - deno fmt README.md
    - gofmt -w .
  lint: golangci-lint run --fix
  test-race: go test -cover --tags "json1 fts5" -race ./...
  test: go test --tags "json1 fts5" ./...
  default:
    cmds:
    - task: format
    - task: lint
    - task: build
    - task: test-race
    - task: test
  