name: 'Go Task'
description: Install go, go-task, golangci-lint, and deno.
inputs:
  github-token:
    description: Github API token
    required: true
runs:
  using: "composite"
  steps:
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    - name: Install golangci-lint
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with: # Grab the latest version
        repo: golangci/golangci-lint
        token: ${{ inputs.github-token }}
        binaries-location: golangci-lint-1.52.0-linux-amd64
        tag: v1.52.0
    - name: Install task
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with: # Grab the latest version
        repo: go-task/task
        token: ${{ inputs.github-token }}
        cache: enable
    - name: Task
      shell: bash
      run: task