# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=10m
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    
    - name: Install Task
      uses: arduino/setup-task@v1

    - name: Task
      run: |
        task ci