# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version: 1.19
    
    - uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: --timeout=10m

    - name: Build and Test with CGO
      run:  |
        export CGO_ENABLED=0
        go build -v ./...
        go test -v ./...

    - name: Build and Test
      run: |
        go build -v ./...
        go test -v -race ./...
