# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    
    - name: Install deps
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with: # Grab the latest version
        repo: golangci/golangci-lint
        cache: true

    - name: Install Task
      uses: arduino/setup-task@v1

    - name: Task
      run: |
        export PATH="/opt/hostedtoolcache/golangci/golangci-lint/latest/linux-x64;$PATH"
        chmod +x /opt/hostedtoolcache/golangci/golangci-lint/latest/linux-x64/golang-ci
        task