# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
    - uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true
        cache: true
    - name: Install minify
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with: # Grab the latest version
        repo: tdewolff/minify
    - name: Install golangci-ling
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with: # Grab the latest version
        repo: golangci/golangci-lint
    - name: Install tasl
      uses: jaxxstorm/action-install-gh-release@v1.9.0
      with: # Grab the latest version
        repo: go-task/task
    - uses: engineerd/configurator@v0.0.10
      with:
        name: minio
        url: https://dl.min.io/server/minio/release/linux-amd64/minio
    - name: Task
      run: |
        task ci